name: federated-learning
dependencies:
  - python==3.9.13
  - pip
  - pip:
    - pandas==1.4.4
    - ipykernel
    - matplotlib
    - seaborn
    - plotly==5.11.0
    - scikit-learn
    - flwr==^1.0.0
    - tensorflow-macos==2.9.1
    - tensorflow-metal==0.6.0

        